# frozen_string_literal: true

# Generated by Rails
module ApplicationHelper
  FLASH_LEVELS = { error: 'alert alert-error',
                   alert: 'alert alert-error',
                   notice: 'alert alert-info',
                   success: 'alert alert-succes' }.freeze

  def bootstrap_class_for(name)
    FLASH_LEVELS[name.to_sym]
  end
end
