# frozen_string_literal: true

# Generated by Rails
module CalendarHelper
  def fill_calendar(bookings)
    require 'icalendar'
    require 'icalendar/tzinfo'
    cal = Icalendar::Calendar.new

    event_start = DateTime.new(2018, 8, 30, 9, 0, 0)
    tzid = 'Europe/Berlin'
    tz = TZInfo::Timezone.get tzid
    timezone = tz.ical_timezone event_start
    cal.add_timezone timezone

    bookings.each do |booking|
      cal.event do |e|
        e.dtstart = Icalendar::Values::DateTime.new(booking.date_in,
                                                    'tzid' => tzid)
        e.dtend   = Icalendar::Values::DateTime.new(booking.date_out,
                                                    'tzid' => tzid)
        e.url = booking_url(booking)
        e.summary = 'Arloff: ' + booking.persons.first.initials
      end
    end
    cal
  end
end
